import assert from 'node:assert/strict';
import { protegerTerminos } from '../extension-udemy/lib/terminosWeb.js';
let ok = 0;
const comprobar = (condicion, mensaje) => { assert.ok(condicion, mensaje); ok++; console.log(`OK: ${mensaje}`); };
const original = '[[JG_SEG_000000]]\nUse JavaScript and Node.js in the backend.\n[[JG_SEG_000001]]\nJavaScript works with React hooks.';
const protegido = protegerTerminos(original);
comprobar(!protegido.texto.includes('JavaScript') && !protegido.texto.includes('Node.js'), 'protege nombres antes de traducir');
comprobar(protegido.texto.includes('[[JG_SEG_000001]]'), 'conserva marcadores temporales');
const traducido = protegido.texto.replace('Use ', 'Usa ').replace(' and ', ' y ').replace(' in the ', ' en el ').replace('works with', 'funciona con');
const salida = protegido.restaurar(traducido);
comprobar(salida.includes('JavaScript y Node.js en el backend'), 'restaura tecnicismos sin guias foneticas');
comprobar(salida.includes('JavaScript funciona con React hooks'), 'conserva repeticiones y frases tecnicas');
comprobar(protegerTerminos('Reactivate the classroom.').texto === 'Reactivate the classroom.', 'no toca fragmentos de otras palabras');
comprobar(protegerTerminos('Hola mundo').restaurar('Hello world') === 'Hello world', 'sin terminos no modifica respuesta');
assert.throws(() => protegido.restaurar('Traduccion incompleta'), /término técnico/); ok++; console.log('OK: no oculta perdida de terminos');
const repetido = protegido.texto + protegido.texto;
assert.throws(() => protegido.restaurar(repetido), /término técnico/); ok++; console.log('OK: detecta terminos duplicados');
const cambiado = protegido.texto.replace('[[JG_SEG_000001]]', '[[JG_SEG_000002]]');
assert.throws(() => protegido.restaurar(cambiado), /término técnico/); ok++; console.log('OK: no cambia tecnicismos de segmento');
const colision = protegerTerminos('JGWEB0X JavaScript');
comprobar(colision.restaurar(colision.texto) === 'JGWEB0X JavaScript', 'no confunde tokens que ya estaban en el original');
console.log(`${ok} comprobaciones OK · 0 fallos`);
