import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { protegerTerminos } from '../js/youtube/terminosWeb.js';
const html = readFileSync(new URL('../index.html', import.meta.url), 'utf8').replace(/\r\n/g, '\n');
function funcion(nombre) {
  const inicio = html.indexOf(`\nfunction ${nombre}(`) + 1;
  assert.ok(inicio > 0);
  const siguiente = html.slice(inicio + 10).search(/\n(?:function |const |let |var |\/\*\*|window\.)/);
  const texto = html.slice(inicio, siguiente < 0 ? html.length : inicio + 10 + siguiente);
  return texto.slice(0, texto.lastIndexOf('}') + 1);
}
let ok = 0;
const comprobar = (c, m) => { assert.ok(c, m); ok++; console.log(`OK: ${m}`); };
const catalogo = new Function('TTS_NEURAL_ACCENTS', 'ttsFishInfo', `${funcion('ttsCatalogoVoces')} return ttsCatalogoVoces();`)([], { active: false });
comprobar(catalogo.some((v) => v.value === 'neural:multi:female'), 'Ava disponible en selector global y PDF');
comprobar(catalogo.some((v) => v.value === 'neural:multi:male'), 'Andrew disponible en selector global y PDF');
const prefs = new Function('jgCfgGet', 'ttsVozActual', 'ttsClaveVoz', `${funcion('ttsNormalizarModo')} ${funcion('ttsPrefs')} return ttsPrefs();`)((k, d) => d, () => ({ provider: 'neural', locale: 'multi', gender: 'female' }), () => 'neural:multi:female');
comprobar(prefs.bilingualMode === 'unified', 'eleccion explicita multilingue prevalece sobre modo anterior');
const corte = new Function(`${funcion('ttsBuscarCorte')} return ttsBuscarCorte;`)();
const ejemplo = 'Si quiero que vuelva por completo al inicio, solo tengo que llamar otra vez a esta función, siempre y cuando la escriba exactamente igual a como la definí al principio.';
const posicion = ejemplo.indexOf(' y cuando');
const sinComas = ejemplo.replaceAll(',', '');
const corteConector = corte(sinComas, sinComas.indexOf(' y cuando'));
comprobar(!/siempre$/.test(sinComas.slice(0, corteConector)), 'corte del primer bloque no divide siempre y cuando');
comprobar(posicion > 0, 'caso exacto del dueño incluido');
const normalizar = new Function(`${funcion('ttsNormalizarTextoNarracion')} return ttsNormalizarTextoNarracion;`)();
const partido = ejemplo.replace('siempre y cuando', 'siempre\n\ny cuando');
comprobar(normalizar(partido, 'es').includes('siempre y cuando'), 'salto de parrafo dentro de una frase no agrega punto');
const protegido = protegerTerminos('[[JG_SEG_0]] Use JavaScript and Node.js. [[JG_SEG_1]] React hooks.');
comprobar(!protegido.texto.includes('JavaScript') && !protegido.texto.includes('Node.js'), 'tecnicismos se protegen antes de traducir');
comprobar(protegido.restaurar(protegido.texto.replace('Use ', 'Usa ')).includes('JavaScript and Node.js'), 'nombres originales se restauran sin reescribirlos');
assert.throws(() => protegido.restaurar(protegido.texto.replace('JGWEB0X', '')), /marcador/); ok++; console.log('OK: termino perdido produce error visible');
assert.throws(() => protegido.restaurar(protegido.texto.replace('JGWEB0X', 'JGWEB0X JGWEB0X')), /marcador/); ok++; console.log('OK: termino duplicado produce error visible');
assert.throws(() => protegido.restaurar(protegido.texto.replace('JGWEB0X', '').replace('[[JG_SEG_1]]', '[[JG_SEG_1]] JGWEB0X')), /marcador/); ok++; console.log('OK: termino cambiado de segmento no se acepta');
console.log(`${ok} comprobaciones OK · 0 fallos`);
